name: Build bundles with PyInstaller

on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            pyinstaller main_mac.spec
          else
            pyinstaller main.spec
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: asteroids-${{ matrix.os }}
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        with:
          tag_name: latest
          files: dist/*
          body: "Automated release of Spacerocks game built with PyInstaller."
